export default {
  USERS_RECEIVED: 'USERS_RECEIVED',
  USER_CREATED: 'USER_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',

  GET_PROFILE: 'GET_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  USER_DELETED: 'USER_DELETED',

  POST_CREATED: 'POST_CREATED',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POST: 'FETCH_POST',
  RECORD_UPDATED: 'RECORD_UPDATED',
  RECORD_DELETED: 'RECORD_DELETED',

  REPLY_CREATED: 'REPLY_CREATED',
  GET_REPLIES: 'GET_REPLIES',
  REPLY_DELETED: 'REPLY_DELETED',
  REPLY_UPDATED: 'REPLY_UPDATED'
};
